name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate static vitepress files
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install

      - run: yarn run docs:build
        env:
          NODE_ENV: production

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd .vitepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@6defe3bd9f0a0846636a7d99ab96ccc75f2c858b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
          branch: gh-pages
          force: true
          directory: .vitepress/dist
